### ISSUE TITLE
Add RSS icon/link for the feed

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap-blog#11]
At the moment while `feed.xml` is generated it's practically hidden.

**Comment by cvrebert** [comment]
Still interested in this?

**Comment by patrickhlauke** [comment]
Although most RSS readers worth their salt have autodiscovery, it would still be nice to have a discreet RSS icon in the footer I'd say (particularly as our audience is more tech savvy, i.e. I can understand why more mainstream sites don't do it anymore)
