### ISSUE TITLE
Bootstrap 4 link in the header is now outdated.

### ISSUE THREAD

**Issue by plaes** [twbs/bootstrap-blog#42]
Current "Aww Yeah,..." link points to blog post made in last August, though there was another update on bootstrap-4 done in December.

**Comment by plaes** [comment]
Gah.. wrong repository, sorry. It's actually in the boostrap gh-pages branch.

**Comment by cvrebert** [comment]
Successor: https://github.com/twbs/bootstrap/issues/19045
