### ISSUE TITLE
Provide Netlify previews

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap-blog#87]
This would make testing PRs like https://github.com/twbs/bootstrap-blog/pull/84 a lot easier.

**Comment by XhmikosR** [comment]
Yup, agreed. We could even switch to Netlify completely to overcome some issues with GitHub pages and custom Jekyll plugins.

**Comment by XhmikosR** [comment]
This was added yesterday by @mdo. :)
